title: "My Awesome Site"
description: "A GitHub Pages site"
theme: jekyll-theme-primer
baseurl: "/pro" # If your project is hosted in a subfolder
url: "https://kicchasudeepa.github.io" # Replace with your GitHub Pages URL
plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata
